version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is in db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    # Remove comment to run on localhost
    #ports:
      #- "3307:3306"