name: A workflow for Group 4 SEM App
on: push

jobs:
  build:
    name: Group 4 SEM
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Compile with Maven
        run: mvn compile
      - name: Run docker compose
        run: docker-compose up --abort-on-container-exit
